version: '3'

services: 
    web:
        build:
            context: ..
            dockerfile: .container/Dockerfile.production
        command: gunicorn root.wsgi:application --bind 0:8000
        expose: 
            - 8000
        env_file: 
            - ./.env.production.web
        volumes:
            - static_volume:/home/coders/production/static
        depends_on:
            - db
    db:
        image: postgres:alpine
        volumes:
            - ../postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.env.production.db
    nginx:
        build:
            context: ..
            dockerfile: .container/NginxDockerfile
        ports:
            - 1337:80
        depends_on:
            - web
        volumes:
            - static_volume:/home/coders/production/static
volumes:
    postgres_data:
    static_volume:
