version: '3'

services: 
    web:
        build:
            context: ..
            dockerfile: .container/Dockerfile
        command: python manage.py runserver 0:8000
        volumes:
            - ..:/workspace
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.dev
    db:
        image: postgres:alpine
        volumes:
            - ../postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=coders
            - POSTGRES_PASSWORD=coders
            - POSTGRES_DB=coders
volumes:
    postgres_data:
